Restrict the scope of optimization disabling in the test suite
When compiled with -O2 -D_FORTIFY_SOURCE=2, deadlock.c gives the
following warning (treated as error):

  In file included from /usr/include/stdio.h:867,
                   from /usr/include/malloc.h:24,
                   from tests/deadlock.c:24:
  In function ‘fgets’,
      inlined from ‘main’ at tests/deadlock.c:104:9:
  /usr/include/bits/stdio2.h:263:9: error: call to ‘__fgets_chk_warn’
  declared with attribute warning: fgets called with bigger size than
  length of destination buffer [-Werror=attribute-warning]
    263 |  return __fgets_chk_warn (__s, __bos (__s), __n, __stream);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

This happens because glibc's fortified functions require optimization.