Handle the return of scanf in the test suite
When compiled with -O2 -D_FORTIFY_SOURCE=2, numserv.c gives the
following warning (treated as error):

  tests/numserv.c: In function ‘main’:
  tests/numserv.c:35:5: error:
    ignoring return value of ‘scanf’, declared with attribute
    warn_unused_result [-Werror=unused-result]
     35 |     scanf("%s", input);
        |     ^~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  make[2]: *** [Makefile:1005: numserv.o] Error 1

Likewise in deadlock.c:

  tests/deadlock.c: In function ‘main’:
  tests/deadlock.c:103:5: error:
    ignoring return value of ‘fgets’ declared with attribute
    ‘warn_unused_result’ [-Werror=unused-result]
    103 |     fgets (buffer, 128, stdin);
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  make[2]: *** [Makefile:1085: deadlock-deadlock.o] Error 1