Fix build with GCC 10
Since GCC 10, libpulp fails to build with the following messages:

  /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld:
    ./.libs/libcommon.a(introspection.o):/home/gabriel/src/libpulp/tools/trigger/introspection.c:69:
    multiple definition of `ulp';
    trigger.o:/home/gabriel/src/libpulp/tools/trigger/trigger.c:39: first defined here
  collect2: error: ld returned 1 exit status

  /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld:
    ./.libs/libcommon.a(introspection.o):/home/gabriel/src/libpulp/tools/trigger/introspection.c:69:
    multiple definition of `ulp';
    check.o:/home/gabriel/src/libpulp/tools/trigger/check.c:39: first defined here
  collect2: error: ld returned 1 exit status

On trigger.c, the ulp variable is not used anywhere, so it can go away,
whereas on check.c, it is used to read the patch Build ID, which has
been parsed into introspection.c's ulp (global variable).