Fix argument to open
The open syscall expects an access mode, such as O_RDONLY, O_WRONLY, or
O_RDWR, not a mode string as fopen.  Passing 'r' to open, opens the file
in an unkown mode, which leads to the following build failures when
_FORTIFY_SOURCE is defined to two:

  gcc [...] -D_FORTIFY_SOURCE=2 -O2 [...]/packer.c
  In file included from /usr/include/fcntl.h:328,
                   from [...]/packer.c:25:
  In function 'open',
      inlined from 'generate_random_patch_id' at [...]/packer.c:507:9:
  /usr/include/bits/fcntl2.h:50:4: error: call to '__open_missing_mode'
  declared with attribute error: open with O_CREAT or O_TMPFILE in
  second argument needs 3 arguments
     50 |    __open_missing_mode ();
        |    ^~~~~~~~~~~~~~~~~~~~~~